/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gyan.parqueadero.interfaz;

import com.gyan.parqueadero.utilidades.Utilidades;
import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;

/**
 *
 * @author libardo
 */
public class GUIConfiguracionTarifas extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIConfiguracionTarifas
     */
    public GUIConfiguracionTarifas() {
        initComponents();
        this.setMaximizable(true);
        this.setResizable(true);
        this.setSize(850, 450);
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlEste = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlOeste = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCarrosTarifaDiurna = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCarrosTarifaTarde = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCarrosTarifaNocturna = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCarrosTarifaMinima = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMotosTarifaDiurna = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMotosTarifaTarde = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMotosTarifaNocturna = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMotosTarifaMinima = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCarrosTarifaMensual = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtMotosTarifaMensual = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCarrosRecargoNocturnoFinSemana = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtMotosRecargoNocturnoFinSemana = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtExtravioTarejeta = new javax.swing.JTextField();
        btnExplicacion = new javax.swing.JButton();

        setClosable(true);
        setTitle("Configuración de Tarifas");

        pnlEste.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/tarifas.png"))); // NOI18N
        pnlEste.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlEste, java.awt.BorderLayout.EAST);

        pnlOeste.setBorder(new javax.swing.border.MatteBorder(null));
        pnlOeste.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Tarifa diurna $:");
        jLabel2.setToolTipText("Tarifa de carros de 7:00 am. a 1:00 pm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel2, gridBagConstraints);

        txtCarrosTarifaDiurna.setText("3500");
        txtCarrosTarifaDiurna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarrosTarifaDiurnaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlOeste.add(txtCarrosTarifaDiurna, gridBagConstraints);

        jLabel3.setText("Tarifa tarde $:");
        jLabel3.setToolTipText("Tarifa de carros de 1:00 pm. a 7:00 pm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel3, gridBagConstraints);

        txtCarrosTarifaTarde.setText("3500");
        txtCarrosTarifaTarde.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlOeste.add(txtCarrosTarifaTarde, gridBagConstraints);

        jLabel4.setText("Tarifa nocturna $:");
        jLabel4.setToolTipText("Tarifa de carros de 7:00 pm. a 7:00 am");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel4, gridBagConstraints);

        txtCarrosTarifaNocturna.setText("7000");
        txtCarrosTarifaNocturna.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlOeste.add(txtCarrosTarifaNocturna, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel5.setText("Carros:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        pnlOeste.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        pnlOeste.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Tarifa mínima $:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel7, gridBagConstraints);

        txtCarrosTarifaMinima.setText("2000");
        txtCarrosTarifaMinima.setToolTipText("Tarifa de la primera hora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlOeste.add(txtCarrosTarifaMinima, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel8.setText("Motos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        pnlOeste.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        pnlOeste.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Tarifa diurna $:");
        jLabel10.setToolTipText("Tarifa de motos de 7:00 am. a 1:00 pm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel10, gridBagConstraints);

        txtMotosTarifaDiurna.setText("2000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlOeste.add(txtMotosTarifaDiurna, gridBagConstraints);

        jLabel11.setText("Tarifa tarde $:");
        jLabel11.setToolTipText("Tarifa de motos de 1:00 pm. a 7:00 pm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel11, gridBagConstraints);

        txtMotosTarifaTarde.setText("2000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlOeste.add(txtMotosTarifaTarde, gridBagConstraints);

        jLabel12.setText("Tarifa nocturna $:");
        jLabel12.setToolTipText("Tarifa de motos de 7:00 pm. a 7:00 am");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel12, gridBagConstraints);

        txtMotosTarifaNocturna.setText("4000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlOeste.add(txtMotosTarifaNocturna, gridBagConstraints);

        jLabel13.setText("Tarifa mínima $:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel13, gridBagConstraints);

        txtMotosTarifaMinima.setText("1000");
        txtMotosTarifaMinima.setToolTipText("Tarifa de la primera hora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlOeste.add(txtMotosTarifaMinima, gridBagConstraints);

        jLabel14.setText("Tarifa mensual $:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel14, gridBagConstraints);

        txtCarrosTarifaMensual.setText("180000");
        txtCarrosTarifaMensual.setToolTipText("Tarifa de todo el mes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlOeste.add(txtCarrosTarifaMensual, gridBagConstraints);

        jLabel15.setText("Tarifa mensual $:");
        jLabel15.setToolTipText("Tarifa de todo el mes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel15, gridBagConstraints);

        txtMotosTarifaMensual.setText("40000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlOeste.add(txtMotosTarifaMensual, gridBagConstraints);

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/grabar.png"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlOeste.add(btnGrabar, gridBagConstraints);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cerrar.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlOeste.add(btnCerrar, gridBagConstraints);

        jLabel16.setText("Nombre Parqueadero:");
        jLabel16.setToolTipText("Este nombre aparecerá en los recibos o facturas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel16, gridBagConstraints);

        txtNombre.setText("jTextField1");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlOeste.add(txtNombre, gridBagConstraints);

        jLabel17.setText("Nit y Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel17, gridBagConstraints);

        txtDireccion.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlOeste.add(txtDireccion, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        pnlOeste.add(jLabel18, gridBagConstraints);

        jLabel19.setText("   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        pnlOeste.add(jLabel19, gridBagConstraints);

        jLabel20.setText("  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        pnlOeste.add(jLabel20, gridBagConstraints);

        jLabel21.setText("Recargo nocturno fin de semana");
        jLabel21.setToolTipText("Recargo que se suma a la tarifa nocturna los dias jueves, viernes y sábado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel21, gridBagConstraints);

        txtCarrosRecargoNocturnoFinSemana.setText("3000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlOeste.add(txtCarrosRecargoNocturnoFinSemana, gridBagConstraints);

        jLabel22.setText("Recargo nocturno fin de semana");
        jLabel22.setToolTipText("Recargo que se suma a la tarifa nocturna los dias jueves, viernes y sábado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel22, gridBagConstraints);

        txtMotosRecargoNocturnoFinSemana.setText("2000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlOeste.add(txtMotosRecargoNocturnoFinSemana, gridBagConstraints);

        jLabel23.setText("Pérdida de tarjeta $:");
        jLabel23.setToolTipText("Recargo adicional por extravío de tarjeta donde está el código de barras");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlOeste.add(jLabel23, gridBagConstraints);

        txtExtravioTarejeta.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlOeste.add(txtExtravioTarejeta, gridBagConstraints);

        btnExplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/mostrarTodos.png"))); // NOI18N
        btnExplicacion.setText("A cerca de las tarifas");
        btnExplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExplicacionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlOeste.add(btnExplicacion, gridBagConstraints);

        getContentPane().add(pnlOeste, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCarrosTarifaDiurnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarrosTarifaDiurnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarrosTarifaDiurnaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        // TODO add your handling code here:
        grabarDatos();
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnExplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExplicacionActionPerformed

        try {
            File path = new File("./src/recursos/EjemplosCobroTarifas.pdf");
            Desktop.getDesktop().open(path);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnExplicacionActionPerformed
    private void cargarDatos() {
        Properties prop = new Properties();
        InputStream is = null;

        try {
            is = new FileInputStream("./config.properties");
            prop.load(is);
        } catch (IOException e) {
            Utilidades.mensajeError("Error al cargar el archivo de configuración de variables\n" + e.getMessage(), "Atencion");
            return;
        }
        txtNombre.setText(prop.getProperty("nombreParqueadero"));
        txtDireccion.setText(prop.getProperty("direccionParqueadero"));

        txtCarrosTarifaDiurna.setText(prop.getProperty("carrosTarifaDiurna"));
        txtCarrosTarifaTarde.setText(prop.getProperty("carrosTarifaTarde"));
        txtCarrosTarifaNocturna.setText(prop.getProperty("carrosTarifaNocturna"));
        txtCarrosTarifaMinima.setText(prop.getProperty("carrosTarifaMinima"));
        txtCarrosTarifaMensual.setText(prop.getProperty("carrosTarifaMensual"));
        txtCarrosRecargoNocturnoFinSemana.setText(prop.getProperty("carrosRecargoNocturnoFinSemana"));

        txtMotosTarifaDiurna.setText(prop.getProperty("motosTarifaDiurna"));
        txtMotosTarifaTarde.setText(prop.getProperty("motosTarifaTarde"));
        txtMotosTarifaNocturna.setText(prop.getProperty("motosTarifaNocturna"));
        txtMotosTarifaMinima.setText(prop.getProperty("motosTarifaMinima"));
        txtMotosTarifaMensual.setText(prop.getProperty("motosTarifaMensual"));
        txtMotosRecargoNocturnoFinSemana.setText(prop.getProperty("motosRecargoNocturnoFinSemana"));

        txtExtravioTarejeta.setText(prop.getProperty("extravioTarjeta"));

    }

    private void grabarDatos() {
        Properties prop = new Properties();
        OutputStream os = null;

        try {
            os = new FileOutputStream("./config.properties");
            prop.setProperty("nombreParqueadero", txtNombre.getText().trim());
            prop.setProperty("direccionParqueadero", txtDireccion.getText().trim());

            prop.setProperty("carrosTarifaDiurna", txtCarrosTarifaDiurna.getText().trim());
            prop.setProperty("carrosTarifaTarde", txtCarrosTarifaTarde.getText());
            prop.setProperty("carrosTarifaNocturna", txtCarrosTarifaNocturna.getText().trim());
            prop.setProperty("carrosTarifaMinima", txtCarrosTarifaMinima.getText().trim());
            prop.setProperty("carrosTarifaMensual", txtCarrosTarifaMensual.getText().trim());
            prop.setProperty("carrosRecargoNocturnoFinSemana", txtCarrosRecargoNocturnoFinSemana.getText().trim());

            prop.setProperty("motosTarifaDiurna", txtMotosTarifaDiurna.getText().trim());
            prop.setProperty("motosTarifaTarde", txtMotosTarifaTarde.getText().trim());
            prop.setProperty("motosTarifaNocturna", txtMotosTarifaNocturna.getText().trim());
            prop.setProperty("motosTarifaMinima", txtMotosTarifaMinima.getText().trim());
            prop.setProperty("motosTarifaMensual", txtMotosTarifaMensual.getText().trim());
            prop.setProperty("motosRecargoNocturnoFinSemana", txtMotosRecargoNocturnoFinSemana.getText().trim());

            prop.setProperty("extravioTarjeta", txtExtravioTarejeta.getText().trim());

            prop.store(os, null);
        } catch (IOException e) {
            Utilidades.mensajeError("Error al grabar en el archivo de configuración de variables\n" + e.getMessage(), "Atencion");
            return;
        }
        Utilidades.mensajeExito("Datos grabados correctamente", "Atencion");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnExplicacion;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlEste;
    private javax.swing.JPanel pnlOeste;
    private javax.swing.JTextField txtCarrosRecargoNocturnoFinSemana;
    private javax.swing.JTextField txtCarrosTarifaDiurna;
    private javax.swing.JTextField txtCarrosTarifaMensual;
    private javax.swing.JTextField txtCarrosTarifaMinima;
    private javax.swing.JTextField txtCarrosTarifaNocturna;
    private javax.swing.JTextField txtCarrosTarifaTarde;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtExtravioTarejeta;
    private javax.swing.JTextField txtMotosRecargoNocturnoFinSemana;
    private javax.swing.JTextField txtMotosTarifaDiurna;
    private javax.swing.JTextField txtMotosTarifaMensual;
    private javax.swing.JTextField txtMotosTarifaMinima;
    private javax.swing.JTextField txtMotosTarifaNocturna;
    private javax.swing.JTextField txtMotosTarifaTarde;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
