/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gyan.parqueadero.interfaz;

import com.gyan.parqueadero.entidades.EntradasSalidas;
import com.gyan.parqueadero.logicanegocio.EntradasSalidasLogicaNegocio;
import com.gyan.parqueadero.utilidades.Utilidades;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author libardo
 */
public class GUIInformeAbierto extends javax.swing.JInternalFrame {


    /**
     * Creates new form GUIInformeIngresosPorFecha
     */
    public GUIInformeAbierto() {
        initComponents();
        //Inicializa las columnas del jTable
        this.inicializarTabla();
        
        this.setSize(900, 680);
    }
    /**
     * Inicializa las columnas del jTable y pone cero filas
     */
    private void inicializarTabla() {
        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Id", "Placa", "Tipo", "Tarifa","FechaEntrada", "FechaSalida", "Descuento", "ValorPagado", "Observación", "EmpleadoEntrada", "EmpleadoSalida"
                }
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentro = new javax.swing.JPanel();
        pnlTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        pnlTotal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        pnlNorte = new javax.swing.JPanel();
        cboMax = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConsulta = new javax.swing.JTextArea();
        btnConsultar = new javax.swing.JButton();
        pnlSur = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Informe  Abierto");

        pnlCentro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlCentro.setLayout(new java.awt.BorderLayout());

        pnlTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResultado);

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
            .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTablaLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addGap(5, 5, 5)))
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
            .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTablaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlCentro.add(pnlTabla, java.awt.BorderLayout.CENTER);

        pnlTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlTotal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel2.setText("Total Registros;");
        pnlTotal.add(jLabel2);

        txtTotal.setEditable(false);
        txtTotal.setText("00000000000000");
        pnlTotal.add(txtTotal);

        pnlCentro.add(pnlTotal, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlNorte.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlNorte.setLayout(new java.awt.GridLayout(3, 2));

        cboMax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "20", "30", "50", "100" }));
        pnlNorte.add(cboMax);

        txtConsulta.setColumns(20);
        txtConsulta.setRows(5);
        txtConsulta.setText("SELECT e FROM EntradasSalidas e WHERE e.fechaHoraEntrada >= '2019-03-01' AND e.fechaHoraEntrada < '2019-04-01'");
        jScrollPane2.setViewportView(txtConsulta);

        pnlNorte.add(jScrollPane2);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        pnlNorte.add(btnConsultar);

        getContentPane().add(pnlNorte, java.awt.BorderLayout.NORTH);

        pnlSur.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pnlSur.add(btnCerrar);

        getContentPane().add(pnlSur, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        buscar();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void buscar() {          

            
        try {
            EntradasSalidasLogicaNegocio logica = new EntradasSalidasLogicaNegocio();
            int max = Integer.parseInt(cboMax.getSelectedItem().toString());
            List<EntradasSalidas> result = logica.consultaAbierta(txtConsulta.getText(), max);
            
            //Llenar los datos en la jTable
            this.inicializarTabla();
            DefaultTableModel model = (DefaultTableModel) tblResultado.getModel();
            
            Object rowData[] = new Object[11];
            for (int i = 0; i < result.size(); i++) {
                rowData[0] = result.get(i).getId();
                rowData[1] = result.get(i).getPlaca().getPlaca();
                rowData[2] = result.get(i).getPlaca().getTipo();//tipo de vehiculo
                rowData[3] = "Horas"; //tarifa
                        
                rowData[4] = Utilidades.formatoFecha(result.get(i).getFechaHoraEntrada());
                if(result.get(i).getFechaHoraSalida() == null){
                    rowData[5] ="";
                }else{
                    rowData[5] = Utilidades.formatoFecha(result.get(i).getFechaHoraSalida());
                }
                    
                rowData[6] = result.get(i).getDescuento();
                rowData[7] = result.get(i).getValorPagar();
                rowData[8] = result.get(i).getObservacion();
                rowData[9] = result.get(i).getEntradaEmpleadosId().getNombres() + " " + result.get(i).getEntradaEmpleadosId().getApellidos();
                if (result.get(i).getSalidaEmpleadosId() == null){
                    rowData[10] = "";
                }else{
                    rowData[10] = result.get(i).getSalidaEmpleadosId().getNombres() + " " + result.get(i).getSalidaEmpleadosId().getApellidos();
                }
                model.addRow(rowData);
            }
            txtTotal.setText("" + result.size());
        } catch (Exception ex) {
            Utilidades.mensajeAdvertencia(ex.getMessage(), "Error en la consulta plsql");
            Logger.getLogger(GUIInformeAbierto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JComboBox<String> cboMax;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSur;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JPanel pnlTotal;
    private javax.swing.JTable tblResultado;
    private javax.swing.JTextArea txtConsulta;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
