/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gyan.parqueadero.interfaz;

import com.gyan.parqueadero.logicanegocio.EntradasSalidasLogicaNegocio;
import com.gyan.parqueadero.utilidades.Utilidades;
import javax.swing.JOptionPane;

/**
 *
 * @author libardo
 */
public class GUIInicializarDatos extends javax.swing.JInternalFrame {

    public GUIInicializarDatos() {
        initComponents();

        //Inicializa las columnas del jTable
        this.setSize(500, 300);
        StringBuilder sb = new StringBuilder(64);
        sb.append("<html><strong>Atención:</strong>Esta opción le permite borrar toda la información del sistema. Se utiliza para inicializar datos. <br>Si esta seguro presione el botón <strong>Aceptar</strong>.</html>");
        lblMensaje.setText(sb.toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentro = new javax.swing.JPanel();
        lblMensaje = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inicializar Datos");

        pnlCentro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlCentro.setLayout(new java.awt.GridLayout(3, 1));

        lblMensaje.setText("Atención: Esta opción le permite borrar todos los registros de la base de datos.");
        pnlCentro.add(lblMensaje);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        pnlCentro.add(btnAceptar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlCentro.add(btnCancelar);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if (Utilidades.mensajeConfirmacion("Está seguro que desea ELIMINAR todos los datos?", "Atención") == JOptionPane.YES_OPTION) {
            EntradasSalidasLogicaNegocio logica = new EntradasSalidasLogicaNegocio();
            logica.inicializarDatos();
            Utilidades.mensajeExito("Los datos se inicializaron con éxito", "Atención");
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JPanel pnlCentro;
    // End of variables declaration//GEN-END:variables
}
