/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gyan.parqueadero.interfaz;

import com.gyan.parqueadero.entidades.Empleados;
import com.gyan.parqueadero.utilidades.Utilidades;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author libardo
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
        //Poner el icono de la aplicación
        Image icon = Toolkit.getDefaultToolkit().getImage("./src/recursos/logo.png");
        this.setIconImage(icon);

        ponerUsuarioLogueado();
        fijarPrivilegios();
    }

    private void ponerUsuarioLogueado() {

        if (Utilidades.empleadoSesion == null) {
            this.mnuEmpleadoLogueado.setText("(Anónimo)");
        } else {
            this.mnuEmpleadoLogueado.setText("(" + Utilidades.empleadoSesion.getNombres() + ")");
        }
    }

    private void fijarPrivilegios() {
        Empleados empleado = Utilidades.empleadoSesion;
        if (empleado != null) {
            if (empleado.getCargo().equals("A")) {
                //Admin
            } else {
                //Empleado normal
                mnuConfiguracion.setVisible(false);
                mnuInformes.setVisible(false);
                mnuGastos.setVisible(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuOpciones = new javax.swing.JMenu();
        mnuEntradasSalidas = new javax.swing.JMenuItem();
        mnuPagosMensuales = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuMisRecaudos = new javax.swing.JMenuItem();
        mnuGastos = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuInformes = new javax.swing.JMenu();
        mnuIngresosPorFecha = new javax.swing.JMenuItem();
        mnuVehiculosEnElParqueadero = new javax.swing.JMenuItem();
        mnuConsultaAbierta = new javax.swing.JMenuItem();
        mnuConfiguracion = new javax.swing.JMenu();
        mnuConfiguracionTarifas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuEmpleados = new javax.swing.JMenuItem();
        btnInicializar = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuAcercaDe = new javax.swing.JMenuItem();
        mnuEmpleadoLogueado = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración de Parqueadero");

        mnuOpciones.setText("Opciones");

        mnuEntradasSalidas.setText("Entradas y salidas");
        mnuEntradasSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEntradasSalidasActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuEntradasSalidas);

        mnuPagosMensuales.setText("Pagos Mensuales");
        mnuPagosMensuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPagosMensualesActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuPagosMensuales);
        mnuOpciones.add(jSeparator1);

        mnuMisRecaudos.setText("Mis recaudos");
        mnuMisRecaudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMisRecaudosActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuMisRecaudos);

        mnuGastos.setText("Gastos");
        mnuGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGastosActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuGastos);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuSalir);

        jMenuBar1.add(mnuOpciones);

        mnuInformes.setText("Informes");

        mnuIngresosPorFecha.setText("Ingresos por vehículo y  fecha");
        mnuIngresosPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIngresosPorFechaActionPerformed(evt);
            }
        });
        mnuInformes.add(mnuIngresosPorFecha);

        mnuVehiculosEnElParqueadero.setText("Vehiculos en el parqueadero");
        mnuVehiculosEnElParqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVehiculosEnElParqueaderoActionPerformed(evt);
            }
        });
        mnuInformes.add(mnuVehiculosEnElParqueadero);

        mnuConsultaAbierta.setText("Consulta Abierta");
        mnuConsultaAbierta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaAbiertaActionPerformed(evt);
            }
        });
        mnuInformes.add(mnuConsultaAbierta);

        jMenuBar1.add(mnuInformes);

        mnuConfiguracion.setText("Configuracion");

        mnuConfiguracionTarifas.setText("Configuración de Tarifas");
        mnuConfiguracionTarifas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConfiguracionTarifasActionPerformed(evt);
            }
        });
        mnuConfiguracion.add(mnuConfiguracionTarifas);
        mnuConfiguracion.add(jSeparator2);

        mnuEmpleados.setText("Empleados");
        mnuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmpleadosActionPerformed(evt);
            }
        });
        mnuConfiguracion.add(mnuEmpleados);

        btnInicializar.setText("Inicializar datos");
        btnInicializar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicializarActionPerformed(evt);
            }
        });
        mnuConfiguracion.add(btnInicializar);

        jMenuBar1.add(mnuConfiguracion);

        mnuAyuda.setText("Ayuda");

        mnuAcercaDe.setText("Acerca de");
        mnuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcercaDeActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuAcercaDe);

        jMenuBar1.add(mnuAyuda);

        mnuEmpleadoLogueado.setBackground(java.awt.Color.magenta);
        mnuEmpleadoLogueado.setText("Usuario_logueado");
        mnuEmpleadoLogueado.setEnabled(false);
        jMenuBar1.add(mnuEmpleadoLogueado);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuEntradasSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEntradasSalidasActionPerformed
        GUIEntradasSalidas ins = new GUIEntradasSalidas();
        ins.setMaximizable(true);

        dskEscritorio.add(ins);
        ins.show();

    }//GEN-LAST:event_mnuEntradasSalidasActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcercaDeActionPerformed
        // TODO add your handling code here:
        String str = "Progrma de parquederos \n"
                + "Version 2.0 - Agosto 8 de 2019 \n"
                + "Programador: wpantoja@gmail.com";
        Utilidades.mensajeExito(str, "Acerca De");
    }//GEN-LAST:event_mnuAcercaDeActionPerformed

    private void mnuIngresosPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIngresosPorFechaActionPerformed
        GUIInformeIngresosPorFecha ins = new GUIInformeIngresosPorFecha(false);
        ins.setMaximizable(true);

        dskEscritorio.add(ins);
        ins.show();


    }//GEN-LAST:event_mnuIngresosPorFechaActionPerformed

    private void mnuVehiculosEnElParqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVehiculosEnElParqueaderoActionPerformed
        GUIVehiculosEnElParqueadero ins = new GUIVehiculosEnElParqueadero();
        ins.setMaximizable(true);

        dskEscritorio.add(ins);
        ins.show();
    }//GEN-LAST:event_mnuVehiculosEnElParqueaderoActionPerformed

    private void mnuConfiguracionTarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConfiguracionTarifasActionPerformed

        GUIConfiguracionTarifas ins = new GUIConfiguracionTarifas();
        ins.setMaximizable(true);

        dskEscritorio.add(ins);
        ins.show();

    }//GEN-LAST:event_mnuConfiguracionTarifasActionPerformed

    private void mnuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmpleadosActionPerformed
        GUIEmpleados ins = new GUIEmpleados();
        ins.setMaximizable(true);

        dskEscritorio.add(ins);
        ins.show();
    }//GEN-LAST:event_mnuEmpleadosActionPerformed

    private void mnuConsultaAbiertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaAbiertaActionPerformed
        GUIInformeAbierto ins = new GUIInformeAbierto();
        ins.setMaximizable(true);

        dskEscritorio.add(ins);
        ins.show();
    }//GEN-LAST:event_mnuConsultaAbiertaActionPerformed

    private void btnInicializarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicializarActionPerformed
        GUIInicializarDatos ins = new GUIInicializarDatos();
        ins.setMaximizable(true);

        dskEscritorio.add(ins);
        ins.show();
    }//GEN-LAST:event_btnInicializarActionPerformed

    private void mnuPagosMensualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPagosMensualesActionPerformed
        GUIPagoMensual ins = new GUIPagoMensual();
        ins.setMaximizable(true);

        dskEscritorio.add(ins);
        ins.show();
    }//GEN-LAST:event_mnuPagosMensualesActionPerformed

    private void mnuMisRecaudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMisRecaudosActionPerformed
        GUIInformeIngresosPorFecha ins = new GUIInformeIngresosPorFecha(true);
        ins.setMaximizable(true);

        dskEscritorio.add(ins);
        ins.show();
    }//GEN-LAST:event_mnuMisRecaudosActionPerformed

    private void mnuGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGastosActionPerformed
        GUIGastos ins = new GUIGastos();
        ins.setMaximizable(true);

        dskEscritorio.add(ins);
        ins.show();
    }//GEN-LAST:event_mnuGastosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIMenu ins = new GUIMenu();
                ins.setExtendedState(MAXIMIZED_BOTH);
                ins.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnInicializar;
    private javax.swing.JDesktopPane dskEscritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuAcercaDe;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuConfiguracion;
    private javax.swing.JMenuItem mnuConfiguracionTarifas;
    private javax.swing.JMenuItem mnuConsultaAbierta;
    private javax.swing.JMenu mnuEmpleadoLogueado;
    private javax.swing.JMenuItem mnuEmpleados;
    private javax.swing.JMenuItem mnuEntradasSalidas;
    private javax.swing.JMenuItem mnuGastos;
    private javax.swing.JMenu mnuInformes;
    private javax.swing.JMenuItem mnuIngresosPorFecha;
    private javax.swing.JMenuItem mnuMisRecaudos;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenuItem mnuPagosMensuales;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuVehiculosEnElParqueadero;
    // End of variables declaration//GEN-END:variables

}
